// Code generated by mockery v2.42.3. DO NOT EDIT.

package mocks

import (
	models "github.com/Atvit/assessment-tax/internals/models"
	mock "github.com/stretchr/testify/mock"
)

// Repository is an autogenerated mock type for the Repository type
type Repository struct {
	mock.Mock
}

// Get provides a mock function with given fields:
func (_m *Repository) Get() (*models.DeductionConfig, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *models.DeductionConfig
	var r1 error
	if rf, ok := ret.Get(0).(func() (*models.DeductionConfig, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() *models.DeductionConfig); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeductionConfig)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Update provides a mock function with given fields: id, entity
func (_m *Repository) Update(id uint, entity *models.DeductionConfigEntity) (*models.DeductionConfig, error) {
	ret := _m.Called(id, entity)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *models.DeductionConfig
	var r1 error
	if rf, ok := ret.Get(0).(func(uint, *models.DeductionConfigEntity) (*models.DeductionConfig, error)); ok {
		return rf(id, entity)
	}
	if rf, ok := ret.Get(0).(func(uint, *models.DeductionConfigEntity) *models.DeductionConfig); ok {
		r0 = rf(id, entity)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.DeductionConfig)
		}
	}

	if rf, ok := ret.Get(1).(func(uint, *models.DeductionConfigEntity) error); ok {
		r1 = rf(id, entity)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewRepository creates a new instance of Repository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *Repository {
	mock := &Repository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
